export const vvtSubtitleContent = `WEBVTT
00:00.917 --> 00:04.462
當初

00:12.053 --> 00:14.305
真不該放招牌

00:15.098 --> 00:17.892
我們到底在想什麼?

00:23.898 --> 00:25.817
是我們引他們來的

00:30.864 --> 00:32.407
我們試著做好事

00:33.450 --> 00:35.910
畢竟我們是人

00:35.994 --> 00:38.079
那現在呢,格瑞斯?

00:53.428 --> 00:57.015
現在

00:57.098 --> 00:59.559
他們似乎很親切
可是我準備走了

01:00.602 --> 01:02.145
我們才剛到這裡

01:02.228 --> 01:04.731
不過,真是的,是該走了

01:05.565 --> 01:07.609
就在我告訴他們華府的事時

01:07.692 --> 01:10.195
當家的混蛋眨眼示意

01:10.278 --> 01:11.321
大夥就掏出槍

01:11.404 --> 01:14.282
立刻引發一場激戰

01:15.241 --> 01:18.912
你們被關進這裡前
有沒有見過泰瑞斯?

01:18.995 --> 01:20.413
-沒有
-很好

01:21.039 --> 01:23.708
漆著白十字架的黑色車

01:23.792 --> 01:25.960
我拼命地追,我盡力了

01:26.461 --> 01:28.755
-她還活著?
-她還活著

01:42.060 --> 01:43.103
在那邊

01:45.730 --> 01:47.107
閉嘴!

01:47.190 --> 01:48.483
好了

01:48.566 --> 01:51.111
有四名混蛋朝我們這邊來了

01:54.030 --> 01:55.490
你們都知道怎麼做
`;

export const srtSubtitleContent1 = `1
00:00:02,300 --> 00:00:05,167
李恩泉 饰金惠仁

2
00:00:06,433 --> 00:00:08,967
金艺琳 饰白济娜 李锺赫 饰徐道言

3
00:00:10,567 --> 00:00:13,333
柳政厚 饰李愿望 韩多瑟 饰吴时恩

4
00:00:15,300 --> 00:00:17,800
张星允 饰金海仁

5
00:00:19,200 --> 00:00:22,867
朴诗雨 饰闵律熙 张德秀 饰朴宇镇

6
00:00:29,167 --> 00:00:34,067
清潭国际高等学校

7
00:00:34,067 --> 00:00:36,600
赞助/文化体育观光部 韩国内容振兴院

8
00:00:36,600 --> 00:00:39,400
本剧之登场人物 团体 企业 事件 机关 地名等 皆纯属虚构 与现实无关

9
00:00:50,833 --> 00:00:53,600
都已经这么努力生活了

10
00:00:53,600 --> 00:00:55,867
人生还是没有什么不同

11
00:00:57,167 --> 00:00:58,767
所以啊

12
00:00:59,700 --> 00:01:01,133
我根本一点也不羡慕

13
00:01:01,133 --> 00:01:04,133
"马上废止清潭国际高中"

14
00:01:04,133 --> 00:01:06,300
"马上废止"

15
00:01:06,300 --> 00:01:08,033
"誓死反对特权教育"

16
00:01:08,033 --> 00:01:09,833
废止清潭国际高中 "誓死反对特权教育"

17
00:01:09,833 --> 00:01:11,767
"贵族学校退下吧"

18
00:01:11,767 --> 00:01:13,633
烦死了

19
00:01:14,267 --> 00:01:15,967
他们到底要抗议到什么时候

20
00:01:15,967 --> 00:01:18,167
深化阶级差距的清潭国际高中 废止才是正道 太羡慕了才会在那边耍脾气吧`;

export const srtSubtitleContent2 = `1
00:00:44,370 --> 00:00:50,460
雷霆沙赞：众神之怒

2
00:01:08,900 --> 00:01:11,150
传说告诉我们 只有少数勇士
The lore tells us of a valiant few.

3
00:01:11,280 --> 00:01:13,530
鑳藉湪鎴樻枟鍜岃糠闆句箣涓惫绔嬩笉鍊�
who stood above the fray and fog.

4
00:01:14,320 --> 00:01:16,570
澶╁摢 浠栦滑涓€瀹氭槸鐢ㄤ簡浠€涔堝ぇ鏉€鍣�
My, what weapons they must have wielded.

5
00:01:17,110 --> 00:01:18,700
杩欏氨瑕佽鍒版垜浠殑灞曞搧浜�
Which brings us to our current exhibit,

6
00:01:19,370 --> 00:01:21,660
绁炶瘽涓殑閭ｆ牴浼楃涔嬫潠
the mythical staff of the gods.

7
00:01:21,990 --> 00:01:24,870
鍦ㄨ嵎椹彶璇椾腑 杩欐牴绁炴潠鍙互鎺у埗
In Homer's tale,

8
00:01:24,960 --> 00:01:27,540
骞朵娇鐢ㄤ紬绁炵殑鍔涢噺
the staff was said to harness the gift of all gods.

9
00:01:29,170 --> 00:01:30,920
娆㈣繋 鍏夎崳鐨勫＋鍏典滑
Oh. Welcome, proud soldiers.

10
00:01:31,130 --> 00:01:33,300
鎴戣杩囧惂 鍗氱墿棣嗗厖婊′箰瓒�
What did I say? Museums are fun.

11
00:01:33,760 --> 00:01:35,420
鏄ぇ鑴戠殑绮剧涔愬洯
Amusement parks for the brains.

12
00:01:37,800 --> 00:01:39,680
娣″畾 涓嶈鎺ㄦ帹鎼℃悺
Okay, there's no reason to get pushy.

13
00:01:39,760 --> 00:01:41,430
姣忎釜浜洪兘鏈夋満浼氬弬瑙�
Everyone will get a chance to see it.

14
00:01:42,060 --> 00:01:46,020
瀹冩槸鐢ㄤ袱鍗冨骞撮毦寰椾竴瑙佺殑蹇冩潗闆曞埢鑰屾垚鐨�
Carved from a heartwood not seen in over 2,000 years,

15
00:01:46,270 --> 00:01:48,350
杩欎欢鏂垚涓ゆ埅鐨勫彜浠ｅ埗鍝�
the two halves of this ancient replica were recently discovered in,

16
00:01:48,560 --> 00:01:49,440
鏄笉涔呭墠
of all places,

17
00:01:49,520 --> 00:01:53,900
鍦ㄨ垂鍩庨儕澶栫殑涓€搴у簾鐗╁鐞嗗巶鍋剁劧鍙戠幇鐨�
a waste processing plant outside of Philadelphia.

18
00:01:54,320 --> 00:01:57,110
瀹冮潪甯稿潥纭� 鎹寮勫潖浜嗕笁鍙板瀮鍦惧帇瀹炴満
So strong, they reportedly broke three trash compactors.

19
00:01:58,070 --> 00:02:00,070
涓嬮潰 鏈嬪弸 涓嶈涔卞姩
Okay, um, friends, that's enough.

20
00:02:00,160 --> 00:02:02,870
澶у搴旇涓撳績鍚垜浠嬬粛 浣忔墜
I'm, I'm sort of the star of the show here... Stop!`;

export const assSubtitleContent1 = `[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
Original Script: 漫游字幕组
Synch Point: 0
ScriptType: v4.00+
PlayResX: 1280
PlayResY: 720
Timer: 100.0000
YCbCr Matrix: TV.601

[Aegisub Project Garbage]
Last Style Storage: Reply.1988.chs
Audio File: Reply.1988.E01.720p.HDTV.x264-AREA11.mkv
Video File: Reply.1988.E01.720p.HDTV.x264-AREA11.mkv
Video AR Mode: 4
Video AR Value: 1.777778
Video Zoom Percent: 0.500000
Scroll Position: 81
Active Line: 83
Video Position: 14117

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Dialogue,Microsoft JhengHei,65,&H00FFFFFF,&H000000FF,&H00AB123B,&H00E05379,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: Comment,DFPKaiShuW7-B5,40,&H00D5D5DD,&H000000FF,&H00464244,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,180,1
Style: Preview,方正卡通简体,48,&H00FFFFFF,&H000000FF,&H003541E9,&H003541E9,-1,0,0,0,100,100,0,0,1,2,1,3,10,30,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:17.60,0:00:19.60,Dialogue,NTP,0,0,0,,{\be3\blur2}1988年
Dialogue: 0,0:00:24.54,0:00:26.47,Dialogue,NTP,0,0,0,,{\be3\blur2}虽然有冷战
Dialogue: 0,0:00:26.47,0:00:28.21,Dialogue,NTP,0,0,0,,{\be3\blur2}但内心火热
Dialogue: 0,0:00:28.21,0:00:29.88,Dialogue,NTP,0,0,0,,{\be3\blur2}虽不富裕
Dialogue: 0,0:00:29.88,0:00:32.75,Dialogue,NTP,0,0,0,,{\be3\blur2}但却有段内心温暖的岁月
Dialogue: 0,0:00:33.15,0:00:36.28,Dialogue,NTP,0,0,0,,{\be3\blur2}当然跟现在比起来
Dialogue: 0,0:00:36.28,0:00:38.49,Dialogue,NTP,0,0,0,,{\be3\blur2}无疑是旧石器时代
Dialogue: 0,0:00:38.49,0:00:41.22,Dialogue,NTP,0,0,0,,{\be3\blur2}是个模拟时代
Dialogue: 0,0:00:41.42,0:00:44.03,Dialogue,NTP,0,0,0,,{\be3\blur2}但是 我们的18岁
Dialogue: 0,0:00:44.03,0:00:46.23,Dialogue,NTP,0,0,0,,{\be3\blur2}自认为是在时代的最前沿
Dialogue: 0,0:00:46.89,0:00:51.16,Dialogue,NTP,0,0,0,,{\be3\blur2}历史上最先开始穿拖鞋式运动鞋
Dialogue: 0,0:00:51.16,0:00:54.24,Dialogue,NTP,0,0,0,,{\be3\blur2}甚至搭配一身牛仔时装
Dialogue: 0,0:00:54.24,0:00:57.24,Dialogue,NTP,0,0,0,,{\be3\blur2}还携带随身听 听着申海澈的歌
Dialogue: 0,0:01:04.18,0:01:08.78,Dialogue,NTP,0,0,0,,{\be3\blur2}男人们为萨默斯还有王祖贤和苏菲玛索
Dialogue: 0,0:01:08.78,0:01:10.92,Dialogue,NTP,0,0,0,,{\be3\blur2}希娜娜老师而疯狂
Dialogue: 0,0:01:11.32,0:01:12.59,Dialogue,NTP,0,0,0,,{\be3\blur2}我们则痴迷于雷明顿斯蒂尔
Dialogue: 0,0:01:12.59,0:01:15.06,Dialogue,NTP,0,0,0,,{\be3\blur2}汤姆克鲁斯 理查基尔
Dialogue: 0,0:01:15.06,0:01:18.19,Dialogue,NTP,0,0,0,,{\be3\blur2}还有新街边男孩的哥哥们
Dialogue: 0,0:01:19.66,0:01:24.27,Dialogue,NTP,0,0,0,,{\be3\blur2}但是不管男女 那时候的年轻人
Dialogue: 0,0:01:24.27,0:01:27.94,Dialogue,NTP,0,0,0,,{\be3\blur2}有一部最爱的电影`;
